In [2]:
import numpy as np

One dimensional array

In [3]:
one_d = np.array([1, 2, 3, 4, 5])

In [4]:
one_d

array([1, 2, 3, 4, 5])

In [5]:
one_d[1]

2

In [6]:
one_d[0]

1

In [7]:
one_d[1]

2

In [8]:
one_d[-1]

5

Two dimensional (Images)

In [9]:
image = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [10]:
image.ndim

2

In [11]:
image.shape

(2, 3)

In [12]:
image[0]

array([1, 2, 3])

In [15]:
image[:,0]

array([1, 4])